### ISSUE TITLE
ERROR DOMException

### ISSUE THREAD

**Issue by jazmandorf** [fido-alliance/fido2-interop-webapp#1]
### **What protocol and version of the protocol are you testing?**
FIDO2 

### **What is the OS or Browser and the version are you running?**
Chrome browser v 69.0.3497.23 beta (64bit)
firefox : 62.0b13(62bit)

### ** Issue description**
**Chrome browser v 69.0.3497.23 beta (64bit)** : 
error :  DOMException: The relying party ID 'https://dev-yus.ydentity.net:9486' is not a registrable domain suffix of, nor equal to 'https://dev-yus.ydentity.net:9486'.

**EDGE browser** : securityError code:18

**FireFox** : DOMException : " The operation is insecure"

It occured error when  runnung **"navigator.credentials.create".**

**Comment by herrjemand** [comment]
Looks like you have incorrectly set RPID in rp.id.
